name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # pin@v6

      # read the hugo version from the .hugo-version file in this repository
      - name: set hugo version
        id: hugo-version
        run: |
          HUGO_VERSION=$(cat .hugo-version)
          echo "HUGO_VERSION=${HUGO_VERSION}" >> $GITHUB_OUTPUT
          echo "Using Hugo version ${HUGO_VERSION}"

      - name: verify vendored hugo cli
        working-directory: bin/vendor
        run: sha256sum --check --strict SHA256SUMS

      # install the hugo cli using the version detected in the previous step
      - name: install vendored hugo cli
        env:
          HUGO_VERSION: ${{ steps.hugo-version.outputs.HUGO_VERSION }}
        run: sudo dpkg -i bin/vendor/hugo_extended_${HUGO_VERSION}_linux-amd64.deb

      # build the site with hugo
      - name: build with hugo
        env:
          GOTOOLCHAIN: local
          GOPROXY: "off"
          HUGO_MODULE_PROXY: "off"
          HUGO_SECURITY_HTTP_URLS: "none"
        run: hugo --gc --minify --logLevel info
